
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int K_RBRKT = 36;
  public static final int STRING_LITERAL = 42;
  public static final int K_CIN = 29;
  public static final int K_BOOL = 21;
  public static final int COMMENT = 39;
  public static final int K_FALSE = 23;
  public static final int O_EQL = 17;
  public static final int K_IF = 25;
  public static final int K_TRUE = 22;
  public static final int WHITESPACE = 38;
  public static final int K_LPAREN = 31;
  public static final int O_LSHIFT = 16;
  public static final int O_NOTEQL = 10;
  public static final int O_COMA = 19;
  public static final int K_VOID = 24;
  public static final int O_SUB = 2;
  public static final int ENDLINE = 37;
  public static final int O_GT = 12;
  public static final int K_RPAREN = 32;
  public static final int O_RSHIFT = 15;
  public static final int K_ELSE = 26;
  public static final int K_COUT = 30;
  public static final int O_DEQL = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int O_GE = 13;
  public static final int O_SEMICOLON = 18;
  public static final int K_RETURN = 28;
  public static final int K_LBRKT = 35;
  public static final int O_AND = 7;
  public static final int K_INT = 20;
  public static final int O_NOT = 6;
  public static final int O_LT = 11;
  public static final int O_DIV = 5;
  public static final int O_OR = 8;
  public static final int O_MULT = 4;
  public static final int K_LSQBKT = 33;
  public static final int O_LE = 14;
  public static final int O_ADD = 3;
  public static final int K_RSQBKT = 34;
  public static final int K_WHILE = 27;
  public static final int INTEGER_LITERAL = 41;
  public static final int IDENTIFIER = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "O_SUB",
  "O_ADD",
  "O_MULT",
  "O_DIV",
  "O_NOT",
  "O_AND",
  "O_OR",
  "O_DEQL",
  "O_NOTEQL",
  "O_LT",
  "O_GT",
  "O_GE",
  "O_LE",
  "O_RSHIFT",
  "O_LSHIFT",
  "O_EQL",
  "O_SEMICOLON",
  "O_COMA",
  "K_INT",
  "K_BOOL",
  "K_TRUE",
  "K_FALSE",
  "K_VOID",
  "K_IF",
  "K_ELSE",
  "K_WHILE",
  "K_RETURN",
  "K_CIN",
  "K_COUT",
  "K_LPAREN",
  "K_RPAREN",
  "K_LSQBKT",
  "K_RSQBKT",
  "K_LBRKT",
  "K_RBRKT",
  "ENDLINE",
  "WHITESPACE",
  "COMMENT",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "STRING_LITERAL"
  };
}

